// Code generated by mockery v1.0.0
package mocks

import (
	context "context"
	"github.com/models"

	mock "github.com/stretchr/testify/mock"
)

// repository is an autogenerated mock type for the repository type
type Repository struct {
	mock.Mock
}
// Fetch provides a mock function with given fields: ctx, cursor, num
func (_m *Repository) GetAll(ctx context.Context,typeApp int)([]*models.VersionApp,error) {
	ret := _m.Called(ctx, typeApp)

	var r0 []*models.VersionApp
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.VersionApp); ok {
		r0 = rf(ctx, typeApp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.VersionApp)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, typeApp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
