// Code generated by mockery v1.0.0
package mocks

import (
	context "context"

	"github.com/models"

	mock "github.com/stretchr/testify/mock"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}
// GetByID provides a mock function with given fields: ctx, id
func (_m *Usecase) 	GetByExperienceID(ctx context.Context, id string) ([]models.ExpPhotosDto, error) {
	ret := _m.Called(ctx, id)

	var r0 []models.ExpPhotosDto
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.ExpPhotosDto); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ExpPhotosDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
