// Code generated by mockery v1.0.0
package mocks

import (
	context "context"
	"github.com/models"

	mock "github.com/stretchr/testify/mock"
)

// repository is an autogenerated mock type for the repository type
type Repository struct {
	mock.Mock
}
// Fetch provides a mock function with given fields: ctx, cursor, num
func (_m *Repository) GetByMerchantID(ctx context.Context, merchantId string) ([]*models.Notification, error) {
	ret := _m.Called(ctx, merchantId)

	var r0 []*models.Notification
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.Notification); ok {
		r0 = rf(ctx, merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Notification)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
// Store provides a mock function with given fields: ctx, a
func (_m *Repository) Insert(ctx context.Context ,notification models.Notification)error {
	ret := _m.Called(ctx, notification)

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.Notification) error); ok {
		r1 = rf(ctx, notification)
	} else {
		r1 = ret.Error(1)
	}

	return r1
}
