// Code generated by mockery v1.0.0
package mocks

import (
	context "context"
	"github.com/models"

	mock "github.com/stretchr/testify/mock"
)

// repository is an autogenerated mock type for the repository type
type Repository struct {
	mock.Mock
}
func (_m *Repository) GetCountDate(ctx context.Context,date string,merchantId string)(int,error) {
	ret := _m.Called(ctx,date,merchantId)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context,string,string) int); ok {
		r0 = rf(ctx,date,merchantId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(int)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context,string,string) error); ok {
		r1 = rf(ctx,date,merchantId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Deletes(ctx context.Context, ids []string, expId string, deletedBy string) error {
	ret := _m.Called(ctx, ids,expId,deletedBy)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string,string,string) error); ok {
		r0 = rf(ctx, ids,expId,deletedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
func (_m *Repository) DeleteByExpId(ctx context.Context,expId string, deletedBy string) error {
	ret := _m.Called(ctx, expId,deletedBy)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string,string) error); ok {
		r0 = rf(ctx, expId,deletedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
func (_m *Repository) GetByExpIds(ctx context.Context, expId []*string,year int,month string) ([]*models.ExpAvailability, error) {
	ret := _m.Called(ctx,expId,year,month)

	var r0 []*models.ExpAvailability
	if rf, ok := ret.Get(0).(func(context.Context,[]*string,int,string) []*models.ExpAvailability); ok {
		r0 = rf(ctx,expId,year,month)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ExpAvailability)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context,[]*string,int,string) error); ok {
		r1 = rf(ctx,expId,year,month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Fetch provides a mock function with given fields: ctx, cursor, num
func (_m *Repository) GetByExpId(ctx context.Context, expId string) ([]*models.ExpAvailability, error) {
	ret := _m.Called(ctx, expId)

	var r0 []*models.ExpAvailability
	if rf, ok := ret.Get(0).(func(context.Context, string) []*models.ExpAvailability); ok {
		r0 = rf(ctx, expId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ExpAvailability)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx,expId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, a
func (_m *Repository) Insert(ctx context.Context, a models.ExpAvailability) (string,error) {
	ret := _m.Called(ctx, a)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, models.ExpAvailability) string); ok {
		r0 = rf(ctx, a)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, models.ExpAvailability) error); ok {
		r1 = rf(ctx, a)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, ar
func (_m *Repository) Update(ctx context.Context, ar models.ExpAvailability) error {
	ret := _m.Called(ctx, ar)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ExpAvailability) error); ok {
		r0 = rf(ctx, ar)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
