// Code generated by mockery v1.0.0
package mocks

import (
	context "context"
	"github.com/models"
)
import mock "github.com/stretchr/testify/mock"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, cursor, num
func (_m *Usecase) GetByType(ctx context.Context, types int) ([]*models.FAQDto, error) {
	ret := _m.Called(ctx, types)

	var r0 []*models.FAQDto
	if rf, ok := ret.Get(0).(func(context.Context,int) []*models.FAQDto); ok {
		r0 = rf(ctx,types)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FAQDto)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, types)
	} else {
		r1 = ret.Error(1)
	}

	return r0,r1
}
